apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 2   # 운영에서는 최소 2개 이상 권장
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      nodeSelector:
        node-role: app   # server-worker에만 스케줄
      containers:
        - name: emqx
          image: emqx/emqx:latest
          ports:
            - containerPort: 1883   # MQTT
            - containerPort: 8083   # MQTT over WebSocket
            - containerPort: 8883   # MQTT over TLS
            - containerPort: 18083  # Dashboard