apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 2   # 운영에서는 최소 2개 이상 권장
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      imagePullSecrets:
      - name: dockerhub-secret

      containers:
      - name: emqx
        image: emqx/emqx:5.3.1
        ports:
        - containerPort: 1883   # MQTT
        - containerPort: 8083   # MQTT over WebSocket
        - containerPort: 8883   # MQTT over TLS
        - containerPort: 18083  # Dashboard
