# postgres-statefulset.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
  namespace: default
spec:
  serviceName: "pg"
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      nodeSelector:
        node-role: db
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: mydb
          volumeMounts:
            - name: pgdata
              mountPath: /pg
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pvc-postgres  # 기존 PVC 사용
---
apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: default
spec:
  type: NodePort
  selector:
    app: pg
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30032
      protocol: TCP
      name: postgres
