apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-postgres
  namespace: default
spec:
  capacity:
    storage: 20Gi # PV 디스크 용량
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pg
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-redis
  namespace: default
spec:
  capacity:
    storage: 10Gi # 추후 10G로 수정
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /redis
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - db