apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31000
