apiVersion: v1
kind: Service
metadata:
  name: emqx-service
  namespace: default
spec:
  type: NodePort   # 내부 개발용은 NodePort, 운영은 LoadBalancer or Ingress 권장
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    nodePort: 32001
  - name: ws
    port: 8083
    targetPort: 8083
    nodePort: 32002
  - name: mqtts
    port: 8883
    targetPort: 8883
    nodePort: 32003
  - name: dashboard
    port: 18083
    targetPort: 18083
    nodePort: 32004
