apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # NodePort 직접 지정 (옵션, 안 쓰면 랜덤)
  type: NodePort
