apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: default
spec:
  selector:
    app: pg
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
   # StatefulSet + Headless Service (DB 접속용)
