---
- name: Deploy applications on Kubernetes
  hosts: k8s-master
  become: true
  tasks:

    # 1. Storage (PV → PVC)
    - name: Apply PersistentVolumes
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/storage/pv.yml') }}"
        wait: yes

    - name: Apply PersistentVolumeClaims
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/storage/pvcs.yml') }}"
        wait: yes

    # 2. Database (Postgres) StatefulSet & Service
    - name: Deploy Postgres
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/deployments/postgres-statefulset.yml') }}"
        wait: yes
        wait_timeout: 300

    # 3. Redis StatefulSet & Service
    - name: Deploy Redis
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/deployments/redis-statefulset.yml') }}"
        wait: yes
        wait_timeout: 300

    # 4. Frontend Deployment & Service
    - name: Deploy Frontend
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/deployments/frontend-deployment.yml') }}"
        wait: yes
        wait_timeout: 300

    - name: Expose Frontend service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/services/frontend-service.yml') }}"

    # 5. Backend (Node.js) Deployment & Service
    - name: Deploy Backend
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/deployments/backend-deployment.yml') }}"

    - name: Expose Backend service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../k8s-manifests/services/backend-service.yml') }}"

#    # 6. Ingress (경로 기반 라우팅)
#    - name: Apply ingress rules
#      kubernetes.core.k8s:
#        state: present
#        definition: "{{ lookup('file', '../k8s-manifests/ingress/ingress-rules.yml') }}"