---
# ===================================================
# 1️⃣ Python3 및 Kubernetes 라이브러리 설치
# ===================================================
- name: Install Python3 and Kubernetes Python client
  hosts: k8s
  become: true
  tasks:
    - name: Check if pip3 is installed
      command: python3 -m pip --version
      register: pip_check
      ignore_errors: yes

    - name: Install python3-pip if pip3 not found
      dnf:
        name: python3-pip
        state: present
      when: pip_check.failed

    - name: Upgrade pip
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install Kubernetes Python client and OpenShift library
      pip:
        name:
          - kubernetes
          - openshift
        executable: pip3

# ===================================================
# 2️⃣ 모든 노드 준비: SELinux, Swap, 필수 패키지
# ===================================================
- name: Prepare all nodes for Kubernetes
  hosts: k8s
  become: true
  tasks:
    - name: Temporarily set SELinux to permissive mode
      command: setenforce 0
      ignore_errors: yes

    - name: Disable SELinux permanently
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=disabled'
      register: selinux_changed

    - name: Reboot if SELinux config changed
      reboot:
        msg: "Rebooting because SELinux was disabled"
        pre_reboot_delay: 2
        reboot_timeout: 300
      when: selinux_changed.changed and inventory_hostname != "ansible-server"

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Remove swap entry from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^(.*swap.*)$'
        replace: '# \1'

    - name: Install required packages
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - curl
          - firewalld
        state: present

    - name: Enable and start firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes

# ===================================================
# 3️⃣ Master 방화벽 포트
# ===================================================
- name: Open firewall ports on Master
  hosts: k8s-master
  become: true
  tasks:
    - name: Open master required ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 6443/tcp
        - 2379-2380/tcp
        - 10250/tcp
        - 10251/tcp
        - 10252/tcp

    - name: Reload firewalld
      command: firewall-cmd --reload

# ===================================================
# 4️⃣ Worker 방화벽 포트
# ===================================================
- name: Open firewall ports on Worker
  hosts: k8s-worker
  become: true
  tasks:
    - name: Open worker required ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 10250/tcp
        - 30000-32767/tcp

    - name: Reload firewalld
      command: firewall-cmd --reload

# ===================================================
# 5️⃣ Docker + Containerd + Kubernetes 설치
# ===================================================
- name: Install Docker, containerd, and Kubernetes
  hosts: k8s
  become: true
  tasks:
    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker and containerd
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config
      command: containerd config default
      register: containerd_default_config

    - name: Write containerd config to /etc/containerd/config.toml
      copy:
        content: "{{ containerd_default_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: Set SystemdCgroup to true in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Enable and restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Add Kubernetes repo
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key

    - name: Install Kubernetes packages
      dnf:
        name:
          - kubelet-1.32.0
          - kubeadm-1.32.0
          - kubectl-1.32.0
        state: present
        disable_excludes: all

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Pull kubeadm required images
      command: kubeadm config images pull
