---
- name: Create PostgreSQL secret in Kubernetes
  hosts: k8s-master
  become: true
  tasks:
    - name: Create pg-secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: pg-secret
            namespace: default
          type: Opaque
          data:
            POSTGRES_USER: "{{ 'mqtteam' | b64encode }}"
            POSTGRES_PASSWORD: "{{ '6666' | b64encode }}"
            POSTGRES_DB: "{{ 'mqtt' | b64encode }}"